export enum ConfigurationEnvEnum {
    GC_GMAIL_CLIENT_ID = "GC_GMAIL_CLIENT_ID",
    GC_GMAIL_CLIENT_SECRET = "GC_GMAIL_CLIENT_SECRET",
    GC_GMAIL_CLIENT_REFRESH_TOKEN = "GC_GMAIL_CLIENT_REFRESH_TOKEN",
}